Update prettier.yml

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -24,12 +24,13 @@ jobs:
       - name: Prettier Check 🔎
         id: prettier
         run: |
-          npx prettier . --check
-          if [ $? -eq 999 ]; then
-            echo "Ignoring error 999 Usually Linkedin"
+          output=$(npx prettier . --check 2>&1) || true
+          echo "$output"
+          if echo "$output" | grep -q "Unknown status (999"; then
+            echo "Ignoring error 999, usually due Linkedin."
           else
-            exit $?
-          fi
+            exit 1
+          fi   
       - name: Create diff 📝
         # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
         if: ${{ failure() }}
